### ISSUE TITLE
home.html Quando eu acrescento a classe com o código: itemSelected(feed):void {... o app não sobe mais

### ISSUE THREAD

**Issue by ghost** [carloscabral/my-reader---Ionic2#1]
![image](https://cloud.githubusercontent.com/assets/7308528/20578817/f0d5f2dc-b1a7-11e6-962a-5fa1b608558a.png)

Olá, 
http://tableless.com.br/criando-uma-aplicacao-movel-com-ionic-2-e-angular-2-em-dez-passos/

quando eu incluo :
    itemSelected (feed):void {
    alert(feed.data.url);
  } 
conforme anexo, o app não sobe mais no navegador

**Comment by carloscabral** [comment]
Esse código tem que estar na classe, não no template. Código JavaScript deve ser escrito dentro do arquivo Home.ts, não em Home.html. O código que você escreveu aí é um método de classe.
