### ISSUE TITLE
problemas pra rodar o aplicativo no device com android

### ISSUE THREAD

**Issue by ghost** [carloscabral/my-reader---Ionic2#3]
![image](https://cloud.githubusercontent.com/assets/7308528/20579581/35462fb4-b1ac-11e6-9a6a-ec45b513cf11.png)

![image](https://cloud.githubusercontent.com/assets/7308528/20579643/a54026d0-b1ac-11e6-8154-e67435242df2.png)

**Comment by carloscabral** [comment]
É um erro com a licença do seu SDK Android. Não fiz o build para Android, apenas para iOS. Parece que você precisa concordar com a licença dessa versão do SDK.
Dê uma olhada: http://stackoverflow.com/questions/40383323/cant-accept-license-agreement-android-sdk-platform-24
